import { MetaType } from '../contracts/enums/MetaType'

export enum ObjectType {
  NoObj = 'NoObj',
  None0 = 'None0',
  DecorativeTown = 'DecorativeTown', // Observed "decorative" Fortress on map "West Orient & Underground Cave" use this
  AltarOfSacrifice = 'AltarOfSacrifice',
  AnchorPoint = 'AnchorPoint',
  Arena = 'Arena',
  Artifact = 'Artifact',
  PandorasBox = 'PandorasBox',
  BlackMarket = 'BlackMarket',
  Boat = 'Boat',
  Borderguard = 'Borderguard',
  Keymaster = 'Keymaster',
  Buoy = 'Buoy',
  Campfire = 'Campfire',
  Cartographer = 'Cartographer',
  SwanPond = 'SwanPond',
  CoverOfDarkness = 'CoverOfDarkness',
  CreatureBank = 'CreatureBank',
  CreatureGenerator1 = 'CreatureGenerator1',
  CreatureGenerator2 = 'CreatureGenerator2',
  CreatureGenerator3 = 'CreatureGenerator3',
  CreatureGenerator4 = 'CreatureGenerator4',
  CursedGround1 = 'CursedGround1',
  Corpse = 'Corpse',
  MarlettoTower = 'MarlettoTower',
  DerelictShip = 'DerelictShip',
  DragonUtopia = 'DragonUtopia',
  Event = 'Event',
  EyeOfMagi = 'EyeOfMagi',
  FaerieRing = 'FaerieRing',
  Flotsam = 'Flotsam',
  FountainOfFortune = 'FountainOfFortune',
  FountainOfYouth = 'FountainOfYouth',
  GardenOfRevelation = 'GardenOfRevelation',
  Garrison = 'Garrison',
  Hero = 'Hero',
  HillFort = 'HillFort',
  Grail = 'Grail',
  HutOfMagi = 'HutOfMagi',
  IdolOfFortune = 'IdolOfFortune',
  LeanTo = 'LeanTo',
  Blank40 = 'Blank40',
  LibraryOfEnlightenment = 'LibraryOfEnlightenment',
  Lighthouse = 'Lighthouse',
  MonolithOneWayEntrance = 'MonolithOneWayEntrance',
  MonolithOneWayExit = 'MonolithOneWayExit',
  MonolithTwoWay = 'MonolithTwoWay',
  MagicPlains1 = 'MagicPlains1',
  SchoolOfMagic = 'SchoolOfMagic',
  MagicSpring = 'MagicSpring',
  MagicWell = 'MagicWell',
  MarketOfTime = 'MarketOfTime',
  MercenaryCamp = 'MercenaryCamp',
  Mermaid = 'Mermaid',
  Mine = 'Mine',
  Creature = 'Creature',
  MysticalGarden = 'MysticalGarden',
  Oasis = 'Oasis',
  Obelisk = 'Obelisk',
  RedwoodObservatory = 'RedwoodObservatory',
  OceanBottle = 'OceanBottle',
  PillarOfFire = 'PillarOfFire',
  StarAxis = 'StarAxis',
  Prison = 'Prison',
  Pyramid = 'Pyramid',
  WogObject = 'WogObject',
  RallyFlag = 'RallyFlag',
  RandomArt = 'RandomArt',
  RandomTreasureArt = 'RandomTreasureArt',
  RandomMinorArt = 'RandomMinorArt',
  RandomMajorArt = 'RandomMajorArt',
  RandomRelicArt = 'RandomRelicArt',
  RandomHero = 'RandomHero',
  RandomCreature = 'RandomCreature',
  RandomCreatureL1 = 'RandomCreatureL1',
  RandomCreatureL2 = 'RandomCreatureL2',
  RandomCreatureL3 = 'RandomCreatureL3',
  RandomCreatureL4 = 'RandomCreatureL4',
  RandomResource = 'RandomResource',
  RandomTown = 'RandomTown',
  RefugeeCamp = 'RefugeeCamp',
  Resource = 'Resource',
  Sanctuary = 'Sanctuary',
  Scholar = 'Scholar',
  SeaChest = 'SeaChest',
  SeerHut = 'SeerHut',
  Crypt = 'Crypt',
  Shipwreck = 'Shipwreck',
  ShipwreckSurvivor = 'ShipwreckSurvivor',
  Shipyard = 'Shipyard',
  ShrineOfMagicIncantation = 'ShrineOfMagicIncantation',
  ShrineOfMagicGesture = 'ShrineOfMagicGesture',
  ShrineOfMagicThought = 'ShrineOfMagicThought',
  Sign = 'Sign',
  Sirens = 'Sirens',
  SpellScroll = 'SpellScroll',
  Stables = 'Stables',
  Tavern = 'Tavern',
  Temple = 'Temple',
  DenOfThieves = 'DenOfThieves',
  Town = 'Town',
  TradingPost = 'TradingPost',
  LearningStone = 'LearningStone',
  TreasureChest = 'TreasureChest',
  TreeOfKnowledge = 'TreeOfKnowledge',
  SubterraneanGate = 'SubterraneanGate',
  University = 'University',
  Wagon = 'Wagon',
  WarMachineFactory = 'WarMachineFactory',
  SchoolOfWar = 'SchoolOfWar',
  WarriorsTomb = 'WarriorsTomb',
  WaterWheel = 'WaterWheel',
  WateringHole = 'WateringHole',
  Whirlpool = 'Whirlpool',
  Windmill = 'Windmill',
  WitchHut = 'WitchHut',
  ImpassableBrush = 'ImpassableBrush',
  ImpassableBush = 'ImpassableBush',
  ImpassableCactus = 'ImpassableCactus',
  ImpassableCanyon = 'ImpassableCanyon',
  ImpassableCrater = 'ImpassableCrater',
  ImpassableDeadvegetation = 'ImpassableDeadvegetation',
  ImpassableFlowers = 'ImpassableFlowers',
  ImpassableFrozenlike = 'ImpassableFrozenlike',
  ImpassableHedge = 'ImpassableHedge',
  ImpassableHill = 'ImpassableHill',
  Hole = 'Hole',
  PassableKelp = 'PassableKelp',
  ImpassableLake = 'ImpassableLake',
  ImpassableLavaflow = 'ImpassableLavaflow',
  ImpassableLavalake = 'ImpassableLavalake',
  ImpassableMushrooms = 'ImpassableMushrooms',
  ImpassableLog = 'ImpassableLog',
  ImpassableMandrake = 'ImpassableMandrake',
  ImpassableMoss = 'ImpassableMoss',
  ImpassableMound = 'ImpassableMound',
  ImpassableMountain = 'ImpassableMountain',
  ImpassableOaktrees = 'ImpassableOaktrees',
  ImpassableOutcropping = 'ImpassableOutcropping',
  ImpassablePinetrees = 'ImpassablePinetrees',
  ImpassablePlant = 'ImpassablePlant',
  Passable139 = 'Passable139', // <blank>
  Passable140 = 'Passable140', // Used for ZRain00 in WoG
  Passable141 = 'Passable141', // <blank>
  Passable142 = 'Passable142', // <blank>
  ImpassableRiverdelta = 'ImpassableRiverdelta',
  Passable144 = 'Passable144', // <blank>
  Passable145 = 'Passable145', // <blank>
  Passable146 = 'Passable146', // <blank>
  ImpassableRock = 'ImpassableRock',
  ImpassableSanddune = 'ImpassableSanddune',
  ImpassableSandpit = 'ImpassableSandpit',
  ImpassableShrub = 'ImpassableShrub',
  ImpassableSkull = 'ImpassableSkull',
  ImpassableStalagmite = 'ImpassableStalagmite',
  ImpassableStump = 'ImpassableStump',
  ImpassableTarpit = 'ImpassableTarpit',
  ImpassableTrees = 'ImpassableTrees',
  ImpassableVine = 'ImpassableVine',
  ImpassableVolcanicvent = 'ImpassableVolcanicvent',
  ImpassableVolcano = 'ImpassableVolcano',
  ImpassableWillowtrees = 'ImpassableWillowtrees',
  ImpassableYuccatrees = 'ImpassableYuccatrees',
  ImpassableReef = 'ImpassableReef',
  RandomCreatureL5 = 'RandomCreatureL5',
  RandomCreatureL6 = 'RandomCreatureL6',
  RandomCreatureL7 = 'RandomCreatureL7',
  ImpassableBrush2 = 'ImpassableBrush2',
  ImpassableBush2 = 'ImpassableBush2',
  ImpassableCactus2 = 'ImpassableCactus2',
  ImpassableCanyon2 = 'ImpassableCanyon2',
  ImpassableCrater2 = 'ImpassableCrater2',
  ImpassableDeadvegetation2 = 'ImpassableDeadvegetation2',
  ImpassableFlowers2 = 'ImpassableFlowers2',
  ImpassableFrozenlike2 = 'ImpassableFrozenlike2',
  ImpassableHedge2 = 'ImpassableHedge2',
  ImpassableHill2 = 'ImpassableHill2',
  PassableHole2 = 'PassableHole2',
  PassableKelp2 = 'PassableKelp2',
  ImpassableLake2 = 'ImpassableLake2',
  ImpassableLavaflow2 = 'ImpassableLavaflow2',
  ImpassableLavalake2 = 'ImpassableLavalake2',
  ImpassableMushrooms2 = 'ImpassableMushrooms2',
  ImpassableLog2 = 'ImpassableLog2',
  ImpassableMandrake2 = 'ImpassableMandrake2',
  ImpassableMoss2 = 'ImpassableMoss2',
  ImpassableMound2 = 'ImpassableMound2',
  ImpassableMountain2 = 'ImpassableMountain2',
  ImpassableOaktrees2 = 'ImpassableOaktrees2',
  ImpassableOutcropping2 = 'ImpassableOutcropping2',
  ImpassablePinetrees2 = 'ImpassablePinetrees2',
  ImpassablePlant2 = 'ImpassablePlant2',
  ImpassableRiverdelta2 = 'ImpassableRiverdelta2',
  ImpassableRock2 = 'ImpassableRock2',
  ImpassableSanddune2 = 'ImpassableSanddune2',
  ImpassableSandpit2 = 'ImpassableSandpit2',
  ImpassableShrub2 = 'ImpassableShrub2',
  ImpassableSkull2 = 'ImpassableSkull2',
  ImpassableStalagmite2 = 'ImpassableStalagmite2',
  ImpassableStump2 = 'ImpassableStump2',
  ImpassableTarpit2 = 'ImpassableTarpit2',
  ImpassableTrees2 = 'ImpassableTrees2',
  ImpassableVine2 = 'ImpassableVine2',
  ImpassableVolcanicvent2 = 'ImpassableVolcanicvent2',
  ImpassableVolcano2 = 'ImpassableVolcano2',
  ImpassableWillowtrees2 = 'ImpassableWillowtrees2',
  ImpassableYuccatrees2 = 'ImpassableYuccatrees2',
  ImpassableReef2 = 'ImpassableReef2',
  ImpassableDeserthills = 'ImpassableDeserthills',
  ImpassableDirthills = 'ImpassableDirthills',
  ImpassableGrasshills = 'ImpassableGrasshills',
  ImpassableRoughhills = 'ImpassableRoughhills',
  ImpassableSubterraneanrocks = 'ImpassableSubterraneanrocks',
  ImpassableSwampFoliage = 'ImpassableSwampFoliage',
  BorderGate = 'BorderGate',
  FreelancersGuild = 'FreelancersGuild',
  HeroPlaceholder = 'HeroPlaceholder',
  QuestGuard = 'QuestGuard',
  RandomDwelling = 'RandomDwelling',
  RandomDwellingLevel = 'RandomDwellingLevel', // subtype creature level
  RandomDwellingAlignment = 'RandomDwellingAlignment', // subtype faction
  Garrison2 = 'Garrison2',
  AbandonedMine = 'AbandonedMine',
  TradingPostSnow = 'TradingPostSnow',
  CloverField = 'CloverField',
  CursedGround2 = 'CursedGround2',
  EvilFog = 'EvilFog',
  FavorableWinds = 'FavorableWinds',
  FieryFields = 'FieryFields',
  HolyGrounds = 'HolyGrounds',
  LucidPools = 'LucidPools',
  MagicClouds = 'MagicClouds',
  MagicPlains2 = 'MagicPlains2',
  Rocklands = 'Rocklands',
}

export const objectTypeEnum = {
  [ObjectType.NoObj]: -1,
  [ObjectType.None0]: 0,
  [ObjectType.DecorativeTown]: 1, // Observed "decorative" Fortress on map "West Orient & Underground Cave" use this
  [ObjectType.AltarOfSacrifice]: 2,
  [ObjectType.AnchorPoint]: 3,
  [ObjectType.Arena]: 4,
  [ObjectType.Artifact]: 5,
  [ObjectType.PandorasBox]: 6,
  [ObjectType.BlackMarket]: 7,
  [ObjectType.Boat]: 8,
  [ObjectType.Borderguard]: 9,
  [ObjectType.Keymaster]: 10,
  [ObjectType.Buoy]: 11,
  [ObjectType.Campfire]: 12,
  [ObjectType.Cartographer]: 13,
  [ObjectType.SwanPond]: 14,
  [ObjectType.CoverOfDarkness]: 15,
  [ObjectType.CreatureBank]: 16,
  [ObjectType.CreatureGenerator1]: 17,
  [ObjectType.CreatureGenerator2]: 18,
  [ObjectType.CreatureGenerator3]: 19,
  [ObjectType.CreatureGenerator4]: 20,
  [ObjectType.CursedGround1]: 21,
  [ObjectType.Corpse]: 22,
  [ObjectType.MarlettoTower]: 23,
  [ObjectType.DerelictShip]: 24,
  [ObjectType.DragonUtopia]: 25,
  [ObjectType.Event]: 26,
  [ObjectType.EyeOfMagi]: 27,
  [ObjectType.FaerieRing]: 28,
  [ObjectType.Flotsam]: 29,
  [ObjectType.FountainOfFortune]: 30,
  [ObjectType.FountainOfYouth]: 31,
  [ObjectType.GardenOfRevelation]: 32,
  [ObjectType.Garrison]: 33,
  [ObjectType.Hero]: 34,
  [ObjectType.HillFort]: 35,
  [ObjectType.Grail]: 36,
  [ObjectType.HutOfMagi]: 37,
  [ObjectType.IdolOfFortune]: 38,
  [ObjectType.LeanTo]: 39,
  [ObjectType.Blank40]: 40,
  [ObjectType.LibraryOfEnlightenment]: 41,
  [ObjectType.Lighthouse]: 42,
  [ObjectType.MonolithOneWayEntrance]: 43,
  [ObjectType.MonolithOneWayExit]: 44,
  [ObjectType.MonolithTwoWay]: 45,
  [ObjectType.MagicPlains1]: 46,
  [ObjectType.SchoolOfMagic]: 47,
  [ObjectType.MagicSpring]: 48,
  [ObjectType.MagicWell]: 49,
  [ObjectType.MarketOfTime]: 50,
  [ObjectType.MercenaryCamp]: 51,
  [ObjectType.Mermaid]: 52,
  [ObjectType.Mine]: 53,
  [ObjectType.Creature]: 54,
  [ObjectType.MysticalGarden]: 55,
  [ObjectType.Oasis]: 56,
  [ObjectType.Obelisk]: 57,
  [ObjectType.RedwoodObservatory]: 58,
  [ObjectType.OceanBottle]: 59,
  [ObjectType.PillarOfFire]: 60,
  [ObjectType.StarAxis]: 61,
  [ObjectType.Prison]: 62,
  [ObjectType.Pyramid]: 63, // subtype 0
  [ObjectType.WogObject]: 63, // subtype > 0
  [ObjectType.RallyFlag]: 64,
  [ObjectType.RandomArt]: 65,
  [ObjectType.RandomTreasureArt]: 66,
  [ObjectType.RandomMinorArt]: 67,
  [ObjectType.RandomMajorArt]: 68,
  [ObjectType.RandomRelicArt]: 69,
  [ObjectType.RandomHero]: 70,
  [ObjectType.RandomCreature]: 71,
  [ObjectType.RandomCreatureL1]: 72,
  [ObjectType.RandomCreatureL2]: 73,
  [ObjectType.RandomCreatureL3]: 74,
  [ObjectType.RandomCreatureL4]: 75,
  [ObjectType.RandomResource]: 76,
  [ObjectType.RandomTown]: 77,
  [ObjectType.RefugeeCamp]: 78,
  [ObjectType.Resource]: 79,
  [ObjectType.Sanctuary]: 80,
  [ObjectType.Scholar]: 81,
  [ObjectType.SeaChest]: 82,
  [ObjectType.SeerHut]: 83,
  [ObjectType.Crypt]: 84,
  [ObjectType.Shipwreck]: 85,
  [ObjectType.ShipwreckSurvivor]: 86,
  [ObjectType.Shipyard]: 87,
  [ObjectType.ShrineOfMagicIncantation]: 88,
  [ObjectType.ShrineOfMagicGesture]: 89,
  [ObjectType.ShrineOfMagicThought]: 90,
  [ObjectType.Sign]: 91,
  [ObjectType.Sirens]: 92,
  [ObjectType.SpellScroll]: 93,
  [ObjectType.Stables]: 94,
  [ObjectType.Tavern]: 95,
  [ObjectType.Temple]: 96,
  [ObjectType.DenOfThieves]: 97,
  [ObjectType.Town]: 98,
  [ObjectType.TradingPost]: 99,
  [ObjectType.LearningStone]: 100,
  [ObjectType.TreasureChest]: 101,
  [ObjectType.TreeOfKnowledge]: 102,
  [ObjectType.SubterraneanGate]: 103,
  [ObjectType.University]: 104,
  [ObjectType.Wagon]: 105,
  [ObjectType.WarMachineFactory]: 106,
  [ObjectType.SchoolOfWar]: 107,
  [ObjectType.WarriorsTomb]: 108,
  [ObjectType.WaterWheel]: 109,
  [ObjectType.WateringHole]: 110,
  [ObjectType.Whirlpool]: 111,
  [ObjectType.Windmill]: 112,
  [ObjectType.WitchHut]: 113,
  [ObjectType.ImpassableBrush]: 114,
  [ObjectType.ImpassableBush]: 115,
  [ObjectType.ImpassableCactus]: 116,
  [ObjectType.ImpassableCanyon]: 117,
  [ObjectType.ImpassableCrater]: 118,
  [ObjectType.ImpassableDeadvegetation]: 119,
  [ObjectType.ImpassableFlowers]: 120,
  [ObjectType.ImpassableFrozenlike]: 121,
  [ObjectType.ImpassableHedge]: 122,
  [ObjectType.ImpassableHill]: 123,
  [ObjectType.Hole]: 124,
  [ObjectType.PassableKelp]: 125,
  [ObjectType.ImpassableLake]: 126,
  [ObjectType.ImpassableLavaflow]: 127,
  [ObjectType.ImpassableLavalake]: 128,
  [ObjectType.ImpassableMushrooms]: 129,
  [ObjectType.ImpassableLog]: 130,
  [ObjectType.ImpassableMandrake]: 131,
  [ObjectType.ImpassableMoss]: 132,
  [ObjectType.ImpassableMound]: 133,
  [ObjectType.ImpassableMountain]: 134,
  [ObjectType.ImpassableOaktrees]: 135,
  [ObjectType.ImpassableOutcropping]: 136,
  [ObjectType.ImpassablePinetrees]: 137,
  [ObjectType.ImpassablePlant]: 138,
  [ObjectType.Passable139]: 139, // <blank>
  [ObjectType.Passable140]: 140, // Used for ZRain00 in WoG
  [ObjectType.Passable141]: 141, // <blank>
  [ObjectType.Passable142]: 142, // <blank>
  [ObjectType.ImpassableRiverdelta]: 143,
  [ObjectType.Passable144]: 144, // <blank>
  [ObjectType.Passable145]: 145, // <blank>
  [ObjectType.Passable146]: 146, // <blank>
  [ObjectType.ImpassableRock]: 147,
  [ObjectType.ImpassableSanddune]: 148,
  [ObjectType.ImpassableSandpit]: 149,
  [ObjectType.ImpassableShrub]: 150,
  [ObjectType.ImpassableSkull]: 151,
  [ObjectType.ImpassableStalagmite]: 152,
  [ObjectType.ImpassableStump]: 153,
  [ObjectType.ImpassableTarpit]: 154,
  [ObjectType.ImpassableTrees]: 155,
  [ObjectType.ImpassableVine]: 156,
  [ObjectType.ImpassableVolcanicvent]: 157,
  [ObjectType.ImpassableVolcano]: 158,
  [ObjectType.ImpassableWillowtrees]: 159,
  [ObjectType.ImpassableYuccatrees]: 160,
  [ObjectType.ImpassableReef]: 161,
  [ObjectType.RandomCreatureL5]: 162,
  [ObjectType.RandomCreatureL6]: 163,
  [ObjectType.RandomCreatureL7]: 164,
  [ObjectType.ImpassableBrush2]: 165,
  [ObjectType.ImpassableBush2]: 166,
  [ObjectType.ImpassableCactus2]: 167,
  [ObjectType.ImpassableCanyon2]: 168,
  [ObjectType.ImpassableCrater2]: 169,
  [ObjectType.ImpassableDeadvegetation2]: 170,
  [ObjectType.ImpassableFlowers2]: 171,
  [ObjectType.ImpassableFrozenlike2]: 172,
  [ObjectType.ImpassableHedge2]: 173,
  [ObjectType.ImpassableHill2]: 174,
  [ObjectType.PassableHole2]: 175,
  [ObjectType.PassableKelp2]: 176,
  [ObjectType.ImpassableLake2]: 177,
  [ObjectType.ImpassableLavaflow2]: 178,
  [ObjectType.ImpassableLavalake2]: 179,
  [ObjectType.ImpassableMushrooms2]: 180,
  [ObjectType.ImpassableLog2]: 181,
  [ObjectType.ImpassableMandrake2]: 182,
  [ObjectType.ImpassableMoss2]: 183,
  [ObjectType.ImpassableMound2]: 184,
  [ObjectType.ImpassableMountain2]: 185,
  [ObjectType.ImpassableOaktrees2]: 186,
  [ObjectType.ImpassableOutcropping2]: 187,
  [ObjectType.ImpassablePinetrees2]: 188,
  [ObjectType.ImpassablePlant2]: 189,
  [ObjectType.ImpassableRiverdelta2]: 190,
  [ObjectType.ImpassableRock2]: 191,
  [ObjectType.ImpassableSanddune2]: 192,
  [ObjectType.ImpassableSandpit2]: 193,
  [ObjectType.ImpassableShrub2]: 194,
  [ObjectType.ImpassableSkull2]: 195,
  [ObjectType.ImpassableStalagmite2]: 196,
  [ObjectType.ImpassableStump2]: 197,
  [ObjectType.ImpassableTarpit2]: 198,
  [ObjectType.ImpassableTrees2]: 199,
  [ObjectType.ImpassableVine2]: 200,
  [ObjectType.ImpassableVolcanicvent2]: 201,
  [ObjectType.ImpassableVolcano2]: 202,
  [ObjectType.ImpassableWillowtrees2]: 203,
  [ObjectType.ImpassableYuccatrees2]: 204,
  [ObjectType.ImpassableReef2]: 205,
  [ObjectType.ImpassableDeserthills]: 206,
  [ObjectType.ImpassableDirthills]: 207,
  [ObjectType.ImpassableGrasshills]: 208,
  [ObjectType.ImpassableRoughhills]: 209,
  [ObjectType.ImpassableSubterraneanrocks]: 210,
  [ObjectType.ImpassableSwampFoliage]: 211,
  [ObjectType.BorderGate]: 212,
  [ObjectType.FreelancersGuild]: 213,
  [ObjectType.HeroPlaceholder]: 214,
  [ObjectType.QuestGuard]: 215,
  [ObjectType.RandomDwelling]: 216,
  [ObjectType.RandomDwellingLevel]: 217, // subtype creature level
  [ObjectType.RandomDwellingAlignment]: 218, // subtype faction
  [ObjectType.Garrison2]: 219,
  [ObjectType.AbandonedMine]: 220,
  [ObjectType.TradingPostSnow]: 221,
  [ObjectType.CloverField]: 222,
  [ObjectType.CursedGround2]: 223,
  [ObjectType.EvilFog]: 224,
  [ObjectType.FavorableWinds]: 225,
  [ObjectType.FieryFields]: 226,
  [ObjectType.HolyGrounds]: 227,
  [ObjectType.LucidPools]: 228,
  [ObjectType.MagicClouds]: 229,
  [ObjectType.MagicPlains2]: 230,
  [ObjectType.Rocklands]: 231,
}

type TypeMap = { [K in ObjectType]: MetaType }

export const objectTypeToMeta: TypeMap = {
  [ObjectType.NoObj]: MetaType.None,
  [ObjectType.None0]: MetaType.ImpassableTerrain,
  [ObjectType.Blank40]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableBrush]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableBush]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCactus]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCanyon]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCrater]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableDeadvegetation]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableFlowers]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableFrozenlike]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableHedge]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableHill]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLake]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLavaflow]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLavalake]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMushrooms]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLog]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMandrake]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMoss]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMound]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMountain]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableOaktrees]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableOutcropping]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassablePinetrees]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassablePlant]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableRiverdelta]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableRock]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSanddune]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSandpit]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableShrub]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSkull]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableStalagmite]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableStump]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableTarpit]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableTrees]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVine]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVolcanicvent]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVolcano]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableWillowtrees]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableYuccatrees]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableReef]: MetaType.ImpassableTerrain,

  // ab
  [ObjectType.ImpassableBrush2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableBush2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCactus2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCanyon2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableCrater2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableDeadvegetation2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableFlowers2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableFrozenlike2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableHedge2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableHill2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLake2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLavaflow2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLavalake2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMushrooms2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableLog2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMandrake2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMoss2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMound2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableMountain2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableOaktrees2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableOutcropping2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassablePinetrees2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassablePlant2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableRiverdelta2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableRock2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSanddune2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSandpit2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableShrub2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSkull2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableStalagmite2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableStump2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableTarpit2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableTrees2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVine2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVolcanicvent2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableVolcano2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableWillowtrees2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableYuccatrees2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableReef2]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableDeserthills]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableDirthills]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableGrasshills]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableRoughhills]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSubterraneanrocks]: MetaType.ImpassableTerrain,
  [ObjectType.ImpassableSwampFoliage]: MetaType.ImpassableTerrain,

  [ObjectType.AltarOfSacrifice]: MetaType.Visitable,
  [ObjectType.AnchorPoint]: MetaType.Visitable,
  [ObjectType.Arena]: MetaType.Visitable,
  [ObjectType.BlackMarket]: MetaType.Visitable,
  [ObjectType.Cartographer]: MetaType.Visitable,
  [ObjectType.Buoy]: MetaType.Visitable,
  [ObjectType.SwanPond]: MetaType.Visitable,
  [ObjectType.CoverOfDarkness]: MetaType.Visitable,
  [ObjectType.CreatureBank]: MetaType.Visitable,
  [ObjectType.Corpse]: MetaType.Visitable,
  [ObjectType.MarlettoTower]: MetaType.Visitable,
  [ObjectType.DerelictShip]: MetaType.Visitable,
  [ObjectType.DragonUtopia]: MetaType.Visitable,
  [ObjectType.EyeOfMagi]: MetaType.Visitable,
  [ObjectType.FaerieRing]: MetaType.Visitable,
  [ObjectType.FountainOfFortune]: MetaType.Visitable,
  [ObjectType.FountainOfYouth]: MetaType.Visitable,
  [ObjectType.GardenOfRevelation]: MetaType.Visitable,
  [ObjectType.HillFort]: MetaType.Visitable,
  [ObjectType.HutOfMagi]: MetaType.Visitable,
  [ObjectType.IdolOfFortune]: MetaType.Visitable,
  [ObjectType.LeanTo]: MetaType.Visitable,
  [ObjectType.LibraryOfEnlightenment]: MetaType.Visitable,

  [ObjectType.SchoolOfMagic]: MetaType.Visitable,
  [ObjectType.MagicSpring]: MetaType.Visitable,
  [ObjectType.MagicWell]: MetaType.Visitable,
  [ObjectType.MercenaryCamp]: MetaType.Visitable,
  [ObjectType.Mermaid]: MetaType.Visitable,
  [ObjectType.MysticalGarden]: MetaType.Visitable,
  [ObjectType.Oasis]: MetaType.Visitable,
  [ObjectType.Obelisk]: MetaType.Visitable,
  [ObjectType.RedwoodObservatory]: MetaType.Visitable,
  [ObjectType.PillarOfFire]: MetaType.Visitable,
  [ObjectType.StarAxis]: MetaType.Visitable,
  [ObjectType.RallyFlag]: MetaType.Visitable,
  [ObjectType.Borderguard]: MetaType.Visitable,
  [ObjectType.Keymaster]: MetaType.Visitable,
  [ObjectType.RefugeeCamp]: MetaType.Visitable,
  [ObjectType.Sanctuary]: MetaType.Visitable,
  [ObjectType.Crypt]: MetaType.Visitable,
  [ObjectType.Shipwreck]: MetaType.Visitable,
  [ObjectType.Sirens]: MetaType.Visitable,
  [ObjectType.Stables]: MetaType.Visitable,
  [ObjectType.Tavern]: MetaType.Visitable,
  [ObjectType.Temple]: MetaType.Visitable,
  [ObjectType.DenOfThieves]: MetaType.Visitable,
  [ObjectType.TradingPost]: MetaType.Visitable,
  [ObjectType.LearningStone]: MetaType.Visitable,
  [ObjectType.TreeOfKnowledge]: MetaType.Visitable,
  [ObjectType.University]: MetaType.Visitable,
  [ObjectType.Wagon]: MetaType.Visitable,
  [ObjectType.WarMachineFactory]: MetaType.Visitable,
  [ObjectType.SchoolOfWar]: MetaType.Visitable,
  [ObjectType.WarriorsTomb]: MetaType.Visitable,
  [ObjectType.WaterWheel]: MetaType.Visitable,
  [ObjectType.WateringHole]: MetaType.Visitable,
  [ObjectType.Whirlpool]: MetaType.Visitable,
  [ObjectType.Windmill]: MetaType.Visitable,
  [ObjectType.MarketOfTime]: MetaType.Visitable,
  [ObjectType.DecorativeTown]: MetaType.Visitable,

  [ObjectType.TradingPostSnow]: MetaType.Visitable,
  [ObjectType.Pyramid]: MetaType.Visitable,
  [ObjectType.BorderGate]: MetaType.Visitable,
  [ObjectType.FreelancersGuild]: MetaType.Visitable,

  [ObjectType.Artifact]: MetaType.Artifact,
  [ObjectType.RandomArt]: MetaType.Artifact,
  [ObjectType.RandomTreasureArt]: MetaType.Artifact,
  [ObjectType.RandomMinorArt]: MetaType.Artifact,
  [ObjectType.RandomMajorArt]: MetaType.Artifact,
  [ObjectType.RandomRelicArt]: MetaType.Artifact,

  [ObjectType.AbandonedMine]: MetaType.AbandonedMine,

  [ObjectType.CreatureGenerator1]: MetaType.Dwelling,
  [ObjectType.CreatureGenerator2]: MetaType.Dwelling,
  [ObjectType.CreatureGenerator3]: MetaType.Dwelling,
  [ObjectType.CreatureGenerator4]: MetaType.Dwelling,

  [ObjectType.Event]: MetaType.Event,

  [ObjectType.Garrison]: MetaType.Garrison,
  [ObjectType.Garrison2]: MetaType.Garrison,

  [ObjectType.Boat]: MetaType.Boat,

  [ObjectType.CloverField]: MetaType.PassableTerrain,
  [ObjectType.EvilFog]: MetaType.PassableTerrain,
  [ObjectType.FavorableWinds]: MetaType.PassableTerrain,
  [ObjectType.FieryFields]: MetaType.PassableTerrain,
  [ObjectType.HolyGrounds]: MetaType.PassableTerrain,
  [ObjectType.LucidPools]: MetaType.PassableTerrain,
  [ObjectType.MagicClouds]: MetaType.PassableTerrain,
  [ObjectType.Rocklands]: MetaType.PassableTerrain,
  [ObjectType.CursedGround2]: MetaType.PassableTerrain,
  [ObjectType.MagicPlains2]: MetaType.PassableTerrain,
  [ObjectType.Passable139]: MetaType.PassableTerrain,
  [ObjectType.Passable140]: MetaType.PassableTerrain,
  [ObjectType.Passable141]: MetaType.PassableTerrain,
  [ObjectType.Passable142]: MetaType.PassableTerrain,
  [ObjectType.Passable144]: MetaType.PassableTerrain,
  [ObjectType.Passable145]: MetaType.PassableTerrain,
  [ObjectType.Passable146]: MetaType.PassableTerrain,

  [ObjectType.Hole]: MetaType.PassableTerrain,
  [ObjectType.CursedGround1]: MetaType.PassableTerrain,
  [ObjectType.MagicPlains1]: MetaType.PassableTerrain,
  [ObjectType.PassableKelp]: MetaType.PassableTerrain,
  [ObjectType.PassableKelp2]: MetaType.PassableTerrain,
  [ObjectType.PassableHole2]: MetaType.PassableTerrain,

  [ObjectType.PandorasBox]: MetaType.PandorasBox,

  [ObjectType.Grail]: MetaType.Grail,

  [ObjectType.Hero]: MetaType.Hero,

  [ObjectType.Lighthouse]: MetaType.Lighthouse,

  [ObjectType.MonolithTwoWay]: MetaType.Visitable,
  [ObjectType.MonolithOneWayEntrance]: MetaType.Visitable,
  [ObjectType.MonolithOneWayExit]: MetaType.Visitable,

  [ObjectType.Creature]: MetaType.Creature,
  [ObjectType.RandomCreature]: MetaType.Creature,
  [ObjectType.RandomCreatureL1]: MetaType.Creature,
  [ObjectType.RandomCreatureL2]: MetaType.Creature,
  [ObjectType.RandomCreatureL3]: MetaType.Creature,
  [ObjectType.RandomCreatureL4]: MetaType.Creature,
  [ObjectType.RandomCreatureL5]: MetaType.Creature,
  [ObjectType.RandomCreatureL6]: MetaType.Creature,
  [ObjectType.RandomCreatureL7]: MetaType.Creature,

  [ObjectType.OceanBottle]: MetaType.OceanBottle,

  [ObjectType.Prison]: MetaType.Prison,

  [ObjectType.QuestGuard]: MetaType.QuestGuard,
  [ObjectType.RandomDwelling]: MetaType.RandomDwelling,
  [ObjectType.RandomDwellingLevel]: MetaType.RandomDwellingLevel,
  [ObjectType.RandomDwellingAlignment]: MetaType.RandomDwellingAlignment,
  [ObjectType.RandomHero]: MetaType.RandomHero,
  [ObjectType.HeroPlaceholder]: MetaType.PlaceholderHero,
  [ObjectType.Resource]: MetaType.Resource,
  [ObjectType.RandomResource]: MetaType.Resource,

  [ObjectType.Mine]: MetaType.ResourceGenerator,
  [ObjectType.Scholar]: MetaType.Scholar,
  [ObjectType.SeerHut]: MetaType.SeersHut,
  [ObjectType.Shipyard]: MetaType.Shipyard,
  [ObjectType.ShrineOfMagicIncantation]: MetaType.Shrine,
  [ObjectType.ShrineOfMagicGesture]: MetaType.Shrine,
  [ObjectType.ShrineOfMagicThought]: MetaType.Shrine,

  [ObjectType.Sign]: MetaType.Sign,
  [ObjectType.SpellScroll]: MetaType.SpellScroll,
  [ObjectType.SubterraneanGate]: MetaType.SubterraneanGate,
  [ObjectType.Town]: MetaType.Town,
  [ObjectType.RandomTown]: MetaType.Town,
  [ObjectType.WitchHut]: MetaType.WitchHut,
  [ObjectType.Campfire]: MetaType.Treasure,
  [ObjectType.Flotsam]: MetaType.Treasure,
  [ObjectType.SeaChest]: MetaType.Treasure,
  [ObjectType.ShipwreckSurvivor]: MetaType.Treasure,
  [ObjectType.TreasureChest]: MetaType.Treasure,

  [ObjectType.WogObject]: MetaType.None,
}

export enum ObjectGroup {
  Towns = 'Towns',
  Creatures = 'Creatures',
  Heroes = 'Heroes',
  Artifacts = 'Artifacts',
  Treasure = 'Treasure',
}

export const objectGroupEnum = {
  [ObjectGroup.Towns]: 1,
  [ObjectGroup.Creatures]: 2,
  [ObjectGroup.Heroes]: 3,
  [ObjectGroup.Artifacts]: 4,
  [ObjectGroup.Treasure]: 5,
}
