export enum Artifact {
  Spellbook,
  SpellScroll,
  Grail,
  Catapult,
  Ballista,
  AmmoCart,
  FirstAidTent,
  CentaurAxe,
  BlackshardOfTheDeadKnight,
  GreaterGnollsFlail,
  OgresClubOfHavoc,
  SwordOfHellfire,
  TitansGladius,
  ShieldOfTheDwarvenLords,
  ShieldOfTheYawningDead,
  BucklerOfTheGnollKing,
  TargOfTheRampagingOgre,
  ShieldOfTheDamned,
  SentinelsShield,
  HelmOfTheAlabasterUnicorn,
  SkullHelmet,
  HelmOfChaos,
  CrownOfTheSupremeMagi,
  HellstormHelmet,
  ThunderHelmet,
  BreastplateOfPetrifiedWood,
  RibCage,
  ScalesOfTheGreaterBasilisk,
  TunicOfTheCyclopsKing,
  BreastplateOfBrimstone,
  TitansCuirass,
  ArmorOfWonder,
  SandalsOfTheSaint,
  CelestialNecklaceOfBliss,
  LionsShieldOfCourage,
  SwordOfJudgement,
  HelmOfHeavenlyEnlightenment,
  QuietEyeOfTheDragon,
  RedDragonFlameTongue,
  DragonScaleShield,
  DragonScaleArmor,
  DragonboneGreaves,
  DragonWingTabard,
  NecklaceOfDragonteeth,
  CrownOfDragontooth,
  StillEyeOfTheDragon,
  CloverOfFortune,
  CardsOfProphecy,
  LadybirdOfLuck,
  BadgeOfCourage,
  CrestOfValor,
  GlyphOfGallantry,
  Speculum,
  Spyglass,
  AmuletOfTheUndertaker,
  VampiresCowl,
  DeadMansBoots,
  GarnitureOfInterference,
  SurcoatOfCounterpoise,
  BootsOfPolarity,
  BowOfElvenCherrywood,
  BowstringOfTheUnicornsMane,
  AngelFeatherArrows,
  BirdOfPerception,
  StoicWatchman,
  EmblemOfCognizance,
  StatesmansMedal,
  DiplomatsRing,
  AmbassadorsSash,
  RingOfTheWayfarer,
  EquestriansGloves,
  NecklaceOfOceanGuidance,
  AngelWings,
  CharmOfMana,
  TalismanOfMana,
  MysticOrbOfMana,
  CollarOfConjuring,
  RingOfConjuring,
  CapeOfConjuring,
  OrbOfTheFirmament,
  OrbOfSilt,
  OrbOfTempestuousFire,
  OrbOfDrivingRain,
  RecantersCloak,
  SpiritOfOppression,
  HourglassOfTheEvilHour,
  TomeOfFireMagic,
  TomeOfAirMagic,
  TomeOfWaterMagic,
  TomeOfEarthMagic,
  BootsOfLevitation,
  GoldenBow,
  SphereOfPermanence,
  OrbOfVulnerability,
  RingOfVitality,
  RingOfLife,
  VialOfLifeblood,
  NecklaceOfSwiftness,
  BootsOfSpeed,
  CapeOfVelocity,
  PendantOfDispassion,
  PendantOfSecondSight,
  PendantOfHoliness,
  PendantOfLife,
  PendantOfDeath,
  PendantOfFreeWill,
  PendantOfNegativity,
  PendantOfTotalRecall,
  PendantOfCourage,
  EverflowingCrystalCloak,
  RingOfInfiniteGems,
  EverpouringVialOfMercury,
  InexhaustibleCartOfOre,
  EversmokingRingOfSulfur,
  InexhaustibleCartOfLumber,
  EndlessSackOfGold,
  EndlessBagOfGold,
  EndlessPurseOfGold,
  LegsOfLegion,
  LoinsOfLegion,
  TorsoOfLegion,
  ArmsOfLegion,
  HeadOfLegion,
  SeaCaptainsHat,
  SpellbindersHat,
  ShacklesOfWar,
  OrbOfInhibition,
  VialOfDragonBlood,
  ArmageddonsBlade,
  AngelicAlliance,
  CloakOfTheUndeadKing,
  ElixirOfLife,
  ArmorOfTheDamned,
  StatueOfLegion,
  PowerOfTheDragonFather,
  TitansThunder,
  AdmiralsHat,
  BowOfTheSharpshooter,
  WizardsWell,
  RingOfTheMagi,
  Cornucopia,
  MagicWand,
  GoldTowerArrow,
  MonstersPower,
  HighlightedSlot,
  ArtifactLock,
  AxeOfSmashing,
  MithrilMail,
  SwordOfSharpness,
  HelmOfImmortality,
  PendantOfSorcery,
  BootsOfHaste,
  BowOfSeeking,
  DragonEyeRing,
  HardenedShield,
  SlavasRingOfPower,
  WarlordsBanner,
  CrimsonShieldOfRetribution,
  BarbarianLordsAxeOfFerocity,
  Dragonheart,
  GateKey,
  BlankHelmet,
  BlankSword,
  BlankShield,
  BlankHornedRing,
  BlankGemmedRing,
  BlankNeckBroach,
  BlankArmor,
  BlankSurcoat,
  BlankBoots,
  BlankHorn
}

export const artifactEnum = {
  [Artifact.Spellbook]: 0,
  [Artifact.SpellScroll]: 1,
  [Artifact.Grail]: 2,
  [Artifact.Catapult]: 3,
  [Artifact.Ballista]: 4,
  [Artifact.AmmoCart]: 5,
  [Artifact.FirstAidTent]: 6,
  [Artifact.CentaurAxe]: 7,
  [Artifact.BlackshardOfTheDeadKnight]: 8,
  [Artifact.GreaterGnollsFlail]: 9,
  [Artifact.OgresClubOfHavoc]: 10,
  [Artifact.SwordOfHellfire]: 11,
  [Artifact.TitansGladius]: 12,
  [Artifact.ShieldOfTheDwarvenLords]: 13,
  [Artifact.ShieldOfTheYawningDead]: 14,
  [Artifact.BucklerOfTheGnollKing]: 15,
  [Artifact.TargOfTheRampagingOgre]: 16,
  [Artifact.ShieldOfTheDamned]: 17,
  [Artifact.SentinelsShield]: 18,
  [Artifact.HelmOfTheAlabasterUnicorn]: 19,
  [Artifact.SkullHelmet]: 20,
  [Artifact.HelmOfChaos]: 21,
  [Artifact.CrownOfTheSupremeMagi]: 22,
  [Artifact.HellstormHelmet]: 23,
  [Artifact.ThunderHelmet]: 24,
  [Artifact.BreastplateOfPetrifiedWood]: 25,
  [Artifact.RibCage]: 26,
  [Artifact.ScalesOfTheGreaterBasilisk]: 27,
  [Artifact.TunicOfTheCyclopsKing]: 28,
  [Artifact.BreastplateOfBrimstone]: 29,
  [Artifact.TitansCuirass]: 30,
  [Artifact.ArmorOfWonder]: 31,
  [Artifact.SandalsOfTheSaint]: 32,
  [Artifact.CelestialNecklaceOfBliss]: 33,
  [Artifact.LionsShieldOfCourage]: 34,
  [Artifact.SwordOfJudgement]: 35,
  [Artifact.HelmOfHeavenlyEnlightenment]: 36,
  [Artifact.QuietEyeOfTheDragon]: 37,
  [Artifact.RedDragonFlameTongue]: 38,
  [Artifact.DragonScaleShield]: 39,
  [Artifact.DragonScaleArmor]: 40,
  [Artifact.DragonboneGreaves]: 41,
  [Artifact.DragonWingTabard]: 42,
  [Artifact.NecklaceOfDragonteeth]: 43,
  [Artifact.CrownOfDragontooth]: 44,
  [Artifact.StillEyeOfTheDragon]: 45,
  [Artifact.CloverOfFortune]: 46,
  [Artifact.CardsOfProphecy]: 47,
  [Artifact.LadybirdOfLuck]: 48,
  [Artifact.BadgeOfCourage]: 49,
  [Artifact.CrestOfValor]: 50,
  [Artifact.GlyphOfGallantry]: 51,
  [Artifact.Speculum]: 52,
  [Artifact.Spyglass]: 53,
  [Artifact.AmuletOfTheUndertaker]: 54,
  [Artifact.VampiresCowl]: 55,
  [Artifact.DeadMansBoots]: 56,
  [Artifact.GarnitureOfInterference]: 57,
  [Artifact.SurcoatOfCounterpoise]: 58,
  [Artifact.BootsOfPolarity]: 59,
  [Artifact.BowOfElvenCherrywood]: 60,
  [Artifact.BowstringOfTheUnicornsMane]: 61,
  [Artifact.AngelFeatherArrows]: 62,
  [Artifact.BirdOfPerception]: 63,
  [Artifact.StoicWatchman]: 64,
  [Artifact.EmblemOfCognizance]: 65,
  [Artifact.StatesmansMedal]: 66,
  [Artifact.DiplomatsRing]: 67,
  [Artifact.AmbassadorsSash]: 68,
  [Artifact.RingOfTheWayfarer]: 69,
  [Artifact.EquestriansGloves]: 70,
  [Artifact.NecklaceOfOceanGuidance]: 71,
  [Artifact.AngelWings]: 72,
  [Artifact.CharmOfMana]: 73,
  [Artifact.TalismanOfMana]: 74,
  [Artifact.MysticOrbOfMana]: 75,
  [Artifact.CollarOfConjuring]: 76,
  [Artifact.RingOfConjuring]: 77,
  [Artifact.CapeOfConjuring]: 78,
  [Artifact.OrbOfTheFirmament]: 79,
  [Artifact.OrbOfSilt]: 80,
  [Artifact.OrbOfTempestuousFire]: 81,
  [Artifact.OrbOfDrivingRain]: 82,
  [Artifact.RecantersCloak]: 83,
  [Artifact.SpiritOfOppression]: 84,
  [Artifact.HourglassOfTheEvilHour]: 85,
  [Artifact.TomeOfFireMagic]: 86,
  [Artifact.TomeOfAirMagic]: 87,
  [Artifact.TomeOfWaterMagic]: 88,
  [Artifact.TomeOfEarthMagic]: 89,
  [Artifact.BootsOfLevitation]: 90,
  [Artifact.GoldenBow]: 91,
  [Artifact.SphereOfPermanence]: 92,
  [Artifact.OrbOfVulnerability]: 93,
  [Artifact.RingOfVitality]: 94,
  [Artifact.RingOfLife]: 95,
  [Artifact.VialOfLifeblood]: 96,
  [Artifact.NecklaceOfSwiftness]: 97,
  [Artifact.BootsOfSpeed]: 98,
  [Artifact.CapeOfVelocity]: 99,
  [Artifact.PendantOfDispassion]: 100,
  [Artifact.PendantOfSecondSight]: 101,
  [Artifact.PendantOfHoliness]: 102,
  [Artifact.PendantOfLife]: 103,
  [Artifact.PendantOfDeath]: 104,
  [Artifact.PendantOfFreeWill]: 105,
  [Artifact.PendantOfNegativity]: 106,
  [Artifact.PendantOfTotalRecall]: 107,
  [Artifact.PendantOfCourage]: 108,
  [Artifact.EverflowingCrystalCloak]: 109,
  [Artifact.RingOfInfiniteGems]: 110,
  [Artifact.EverpouringVialOfMercury]: 111,
  [Artifact.InexhaustibleCartOfOre]: 112,
  [Artifact.EversmokingRingOfSulfur]: 113,
  [Artifact.InexhaustibleCartOfLumber]: 114,
  [Artifact.EndlessSackOfGold]: 115,
  [Artifact.EndlessBagOfGold]: 116,
  [Artifact.EndlessPurseOfGold]: 117,
  [Artifact.LegsOfLegion]: 118,
  [Artifact.LoinsOfLegion]: 119,
  [Artifact.TorsoOfLegion]: 120,
  [Artifact.ArmsOfLegion]: 121,
  [Artifact.HeadOfLegion]: 122,
  [Artifact.SeaCaptainsHat]: 123,
  [Artifact.SpellbindersHat]: 124,
  [Artifact.ShacklesOfWar]: 125,
  [Artifact.OrbOfInhibition]: 126,
  [Artifact.VialOfDragonBlood]: 127,
  [Artifact.ArmageddonsBlade]: 128,
  [Artifact.AngelicAlliance]: 129,
  [Artifact.CloakOfTheUndeadKing]: 130,
  [Artifact.ElixirOfLife]: 131,
  [Artifact.ArmorOfTheDamned]: 132,
  [Artifact.StatueOfLegion]: 133,
  [Artifact.PowerOfTheDragonFather]: 134,
  [Artifact.TitansThunder]: 135,
  [Artifact.AdmiralsHat]: 136,
  [Artifact.BowOfTheSharpshooter]: 137,
  [Artifact.WizardsWell]: 138,
  [Artifact.RingOfTheMagi]: 139,
  [Artifact.Cornucopia]: 140,
  [Artifact.MagicWand]: 141,
  [Artifact.GoldTowerArrow]: 142,
  [Artifact.MonstersPower]: 143,
  [Artifact.HighlightedSlot]: 144,
  [Artifact.ArtifactLock]: 145,
  [Artifact.AxeOfSmashing]: 146,
  [Artifact.MithrilMail]: 147,
  [Artifact.SwordOfSharpness]: 148,
  [Artifact.HelmOfImmortality]: 149,
  [Artifact.PendantOfSorcery]: 150,
  [Artifact.BootsOfHaste]: 151,
  [Artifact.BowOfSeeking]: 152,
  [Artifact.DragonEyeRing]: 153,
  [Artifact.HardenedShield]: 154,
  [Artifact.SlavasRingOfPower]: 155,
  [Artifact.WarlordsBanner]: 156,
  [Artifact.CrimsonShieldOfRetribution]: 157,
  [Artifact.BarbarianLordsAxeOfFerocity]: 158,
  [Artifact.Dragonheart]: 159,
  [Artifact.GateKey]: 160,
  [Artifact.BlankHelmet]: 161,
  [Artifact.BlankSword]: 162,
  [Artifact.BlankShield]: 163,
  [Artifact.BlankHornedRing]: 164,
  [Artifact.BlankGemmedRing]: 165,
  [Artifact.BlankNeckBroach]: 166,
  [Artifact.BlankArmor]: 167,
  [Artifact.BlankSurcoat]: 168,
  [Artifact.BlankBoots]: 169,
  [Artifact.BlankHorn]: 170
}
