export enum Skill {
  Pathfinding,
  Archery,
  Logistics,
  Scouting,
  Diplomacy,
  Navigation,
  Leadership,
  Wisdom,
  Mysticism,
  Luck,
  Ballistics,
  EagleEye,
  Necromancy,
  Estates,
  FireMagic,
  AirMagic,
  WaterMagic,
  EarthMagic,
  Scholar,
  Tactics,
  Artillery,
  Learning,
  Offense,
  Armorer,
  Intelligence,
  Sorcery,
  Resistance,
  FirstAid
}

export const skillEnum = {
  [Skill.Pathfinding]: 0x00,
  [Skill.Archery]: 0x01,
  [Skill.Logistics]: 0x02,
  [Skill.Scouting]: 0x03,
  [Skill.Diplomacy]: 0x04,
  [Skill.Navigation]: 0x05,
  [Skill.Leadership]: 0x06,
  [Skill.Wisdom]: 0x07,
  [Skill.Mysticism]: 0x08,
  [Skill.Luck]: 0x09,
  [Skill.Ballistics]: 0x0a,
  [Skill.EagleEye]: 0x0b,
  [Skill.Necromancy]: 0x0c,
  [Skill.Estates]: 0x0d,
  [Skill.FireMagic]: 0x0e,
  [Skill.AirMagic]: 0x0f,
  [Skill.WaterMagic]: 0x10,
  [Skill.EarthMagic]: 0x11,
  [Skill.Scholar]: 0x12,
  [Skill.Tactics]: 0x13,
  [Skill.Artillery]: 0x14,
  [Skill.Learning]: 0x15,
  [Skill.Offense]: 0x16,
  [Skill.Armorer]: 0x17,
  [Skill.Intelligence]: 0x18,
  [Skill.Sorcery]: 0x19,
  [Skill.Resistance]: 0x1a,
  [Skill.FirstAid]: 0x1b
}
