export enum Spell {
  SummonBoat,
  ScuttleBoat,
  Visions,
  ViewEarth,
  Disguise,
  ViewAir,
  Fly,
  WaterWalk,
  DimensionDoor,
  TownPortal,
  QuickSand,
  LandMine,
  ForceField,
  FireWall,
  Earthquake,
  MagicArrow,
  IceBolt,
  LightningBolt,
  Implosion,
  ChainLightning,
  FrostRing,
  Fireball,
  Inferno,
  MeteorShower,
  DeathRipple,
  DestroyUndead,
  Armageddon,
  Shield,
  AirShield,
  FireShield,
  ProtectionFromAir,
  ProtectionFromFire,
  ProtectionFromWater,
  ProtectionFromEarth,
  AntiMagic,
  Dispel,
  MagicMirror,
  Cure,
  Resurrection,
  AnimateDead,
  Sacrifice,
  Bless,
  Curse,
  Bloodlust,
  Precision,
  Weakness,
  StoneSkin,
  DisruptingRay,
  Prayer,
  Mirth,
  Sorrow,
  Fortune,
  Misfortune,
  Haste,
  Slow,
  Slayer,
  Frenzy,
  TitansLightningBolt,
  Counterstrike,
  Berserk,
  Hypnotize,
  Forgetfulness,
  Blind,
  Teleport,
  RemoveObstacle,
  Clone,
  FireElemental,
  EarthElemental,
  WaterElemental,
  AirElemental,
  Stone,
  Poison,
  Pind,
  Disease,
  Paralyze,
  Aging,
  DeathCloud,
  Thunderbolt,
  DragonflyDispel,
  DeathStare,
  AcidBreath
}

export const spellEnum = {
  [Spell.SummonBoat]: 0x00,
  [Spell.ScuttleBoat]: 0x01,
  [Spell.Visions]: 0x02,
  [Spell.ViewEarth]: 0x03,
  [Spell.Disguise]: 0x04,
  [Spell.ViewAir]: 0x05,
  [Spell.Fly]: 0x06,
  [Spell.WaterWalk]: 0x07,
  [Spell.DimensionDoor]: 0x08,
  [Spell.TownPortal]: 0x09,
  [Spell.QuickSand]: 0x0a,
  [Spell.LandMine]: 0x0b,
  [Spell.ForceField]: 0x0c,
  [Spell.FireWall]: 0x0d,
  [Spell.Earthquake]: 0x0e,
  [Spell.MagicArrow]: 0x0f,
  [Spell.IceBolt]: 0x10,
  [Spell.LightningBolt]: 0x11,
  [Spell.Implosion]: 0x12,
  [Spell.ChainLightning]: 0x13,
  [Spell.FrostRing]: 0x14,
  [Spell.Fireball]: 0x15,
  [Spell.Inferno]: 0x16,
  [Spell.MeteorShower]: 0x17,
  [Spell.DeathRipple]: 0x18,
  [Spell.DestroyUndead]: 0x19,
  [Spell.Armageddon]: 0x1a,
  [Spell.Shield]: 0x1b,
  [Spell.AirShield]: 0x1c,
  [Spell.FireShield]: 0x1d,
  [Spell.ProtectionFromAir]: 0x1e,
  [Spell.ProtectionFromFire]: 0x1f,
  [Spell.ProtectionFromWater]: 0x20,
  [Spell.ProtectionFromEarth]: 0x21,
  [Spell.AntiMagic]: 0x22,
  [Spell.Dispel]: 0x23,
  [Spell.MagicMirror]: 0x24,
  [Spell.Cure]: 0x25,
  [Spell.Resurrection]: 0x26,
  [Spell.AnimateDead]: 0x27,
  [Spell.Sacrifice]: 0x28,
  [Spell.Bless]: 0x29,
  [Spell.Curse]: 0x2a,
  [Spell.Bloodlust]: 0x2b,
  [Spell.Precision]: 0x2c,
  [Spell.Weakness]: 0x2d,
  [Spell.StoneSkin]: 0x2e,
  [Spell.DisruptingRay]: 0x2f,
  [Spell.Prayer]: 0x30,
  [Spell.Mirth]: 0x31,
  [Spell.Sorrow]: 0x32,
  [Spell.Fortune]: 0x33,
  [Spell.Misfortune]: 0x34,
  [Spell.Haste]: 0x35,
  [Spell.Slow]: 0x36,
  [Spell.Slayer]: 0x37,
  [Spell.Frenzy]: 0x38,
  [Spell.TitansLightningBolt]: 0x39,
  [Spell.Counterstrike]: 0x3a,
  [Spell.Berserk]: 0x3b,
  [Spell.Hypnotize]: 0x3c,
  [Spell.Forgetfulness]: 0x3d,
  [Spell.Blind]: 0x3e,
  [Spell.Teleport]: 0x3f,
  [Spell.RemoveObstacle]: 0x40,
  [Spell.Clone]: 0x41,
  [Spell.FireElemental]: 0x42,
  [Spell.EarthElemental]: 0x43,
  [Spell.WaterElemental]: 0x44,
  [Spell.AirElemental]: 0x45,
  // these abilities are used in combat creature structures
  [Spell.Stone]: 0x46,
  [Spell.Poison]: 0x47,
  [Spell.Pind]: 0x48,
  [Spell.Disease]: 0x49,
  [Spell.Paralyze]: 0x4a,
  [Spell.Aging]: 0x4b,
  [Spell.DeathCloud]: 0x4c,
  [Spell.Thunderbolt]: 0x4d,
  [Spell.DragonflyDispel]: 0x4e,
  [Spell.DeathStare]: 0x4f,
  [Spell.AcidBreath]: 0x50
}
