import { bytes } from 'binary-markup'
import { bitMasksArray } from '../../../helpers/objects'

export enum Spell {
  SummonBoat = 'SummonBoat',
  ScuttleBoat = 'ScuttleBoat',
  Visions = 'Visions',
  ViewEarth = 'ViewEarth',
  Disguise = 'Disguise',
  ViewAir = 'ViewAir',
  Fly = 'Fly',
  WaterWalk = 'WaterWalk',
  DimensionDoor = 'DimensionDoor',
  TownPortal = 'TownPortal',
  QuickSand = 'QuickSand',
  LandMine = 'LandMine',
  ForceField = 'ForceField',
  FireWall = 'FireWall',
  Earthquake = 'Earthquake',
  MagicArrow = 'MagicArrow',
  IceBolt = 'IceBolt',
  LightningBolt = 'LightningBolt',
  Implosion = 'Implosion',
  ChainLightning = 'ChainLightning',
  FrostRing = 'FrostRing',
  Fireball = 'Fireball',
  Inferno = 'Inferno',
  MeteorShower = 'MeteorShower',
  DeathRipple = 'DeathRipple',
  DestroyUndead = 'DestroyUndead',
  Armageddon = 'Armageddon',
  Shield = 'Shield',
  AirShield = 'AirShield',
  FireShield = 'FireShield',
  ProtectionFromAir = 'ProtectionFromAir',
  ProtectionFromFire = 'ProtectionFromFire',
  ProtectionFromWater = 'ProtectionFromWater',
  ProtectionFromEarth = 'ProtectionFromEarth',
  AntiMagic = 'AntiMagic',
  Dispel = 'Dispel',
  MagicMirror = 'MagicMirror',
  Cure = 'Cure',
  Resurrection = 'Resurrection',
  AnimateDead = 'AnimateDead',
  Sacrifice = 'Sacrifice',
  Bless = 'Bless',
  Curse = 'Curse',
  Bloodlust = 'Bloodlust',
  Precision = 'Precision',
  Weakness = 'Weakness',
  StoneSkin = 'StoneSkin',
  DisruptingRay = 'DisruptingRay',
  Prayer = 'Prayer',
  Mirth = 'Mirth',
  Sorrow = 'Sorrow',
  Fortune = 'Fortune',
  Misfortune = 'Misfortune',
  Haste = 'Haste',
  Slow = 'Slow',
  Slayer = 'Slayer',
  Frenzy = 'Frenzy',
  TitansLightningBolt = 'TitansLightningBolt',
  Counterstrike = 'Counterstrike',
  Berserk = 'Berserk',
  Hypnotize = 'Hypnotize',
  Forgetfulness = 'Forgetfulness',
  Blind = 'Blind',
  Teleport = 'Teleport',
  RemoveObstacle = 'RemoveObstacle',
  Clone = 'Clone',
  FireElemental = 'FireElemental',
  EarthElemental = 'EarthElemental',
  WaterElemental = 'WaterElemental',
  AirElemental = 'AirElemental',
  Stone = 'Stone',
  Poison = 'Poison',
  Pind = 'Pind',
  Disease = 'Disease',
  Paralyze = 'Paralyze',
  Aging = 'Aging',
  DeathCloud = 'DeathCloud',
  Thunderbolt = 'Thunderbolt',
  DragonflyDispel = 'DragonflyDispel',
  DeathStare = 'DeathStare',
  AcidBreath = 'AcidBreath',
}

export const spellEnum = {
  [Spell.SummonBoat]: 0x00,
  [Spell.ScuttleBoat]: 0x01,
  [Spell.Visions]: 0x02,
  [Spell.ViewEarth]: 0x03,
  [Spell.Disguise]: 0x04,
  [Spell.ViewAir]: 0x05,
  [Spell.Fly]: 0x06,
  [Spell.WaterWalk]: 0x07,
  [Spell.DimensionDoor]: 0x08,
  [Spell.TownPortal]: 0x09,
  [Spell.QuickSand]: 0x0a,
  [Spell.LandMine]: 0x0b,
  [Spell.ForceField]: 0x0c,
  [Spell.FireWall]: 0x0d,
  [Spell.Earthquake]: 0x0e,
  [Spell.MagicArrow]: 0x0f,
  [Spell.IceBolt]: 0x10,
  [Spell.LightningBolt]: 0x11,
  [Spell.Implosion]: 0x12,
  [Spell.ChainLightning]: 0x13,
  [Spell.FrostRing]: 0x14,
  [Spell.Fireball]: 0x15,
  [Spell.Inferno]: 0x16,
  [Spell.MeteorShower]: 0x17,
  [Spell.DeathRipple]: 0x18,
  [Spell.DestroyUndead]: 0x19,
  [Spell.Armageddon]: 0x1a,
  [Spell.Shield]: 0x1b,
  [Spell.AirShield]: 0x1c,
  [Spell.FireShield]: 0x1d,
  [Spell.ProtectionFromAir]: 0x1e,
  [Spell.ProtectionFromFire]: 0x1f,
  [Spell.ProtectionFromWater]: 0x20,
  [Spell.ProtectionFromEarth]: 0x21,
  [Spell.AntiMagic]: 0x22,
  [Spell.Dispel]: 0x23,
  [Spell.MagicMirror]: 0x24,
  [Spell.Cure]: 0x25,
  [Spell.Resurrection]: 0x26,
  [Spell.AnimateDead]: 0x27,
  [Spell.Sacrifice]: 0x28,
  [Spell.Bless]: 0x29,
  [Spell.Curse]: 0x2a,
  [Spell.Bloodlust]: 0x2b,
  [Spell.Precision]: 0x2c,
  [Spell.Weakness]: 0x2d,
  [Spell.StoneSkin]: 0x2e,
  [Spell.DisruptingRay]: 0x2f,
  [Spell.Prayer]: 0x30,
  [Spell.Mirth]: 0x31,
  [Spell.Sorrow]: 0x32,
  [Spell.Fortune]: 0x33,
  [Spell.Misfortune]: 0x34,
  [Spell.Haste]: 0x35,
  [Spell.Slow]: 0x36,
  [Spell.Slayer]: 0x37,
  [Spell.Frenzy]: 0x38,
  [Spell.TitansLightningBolt]: 0x39,
  [Spell.Counterstrike]: 0x3a,
  [Spell.Berserk]: 0x3b,
  [Spell.Hypnotize]: 0x3c,
  [Spell.Forgetfulness]: 0x3d,
  [Spell.Blind]: 0x3e,
  [Spell.Teleport]: 0x3f,
  [Spell.RemoveObstacle]: 0x40,
  [Spell.Clone]: 0x41,
  [Spell.FireElemental]: 0x42,
  [Spell.EarthElemental]: 0x43,
  [Spell.WaterElemental]: 0x44,
  [Spell.AirElemental]: 0x45,
  // these abilities are used in combat creature structures
  [Spell.Stone]: 0x46,
  [Spell.Poison]: 0x47,
  [Spell.Pind]: 0x48,
  [Spell.Disease]: 0x49,
  [Spell.Paralyze]: 0x4a,
  [Spell.Aging]: 0x4b,
  [Spell.DeathCloud]: 0x4c,
  [Spell.Thunderbolt]: 0x4d,
  [Spell.DragonflyDispel]: 0x4e,
  [Spell.DeathStare]: 0x4f,
  [Spell.AcidBreath]: 0x50,
}

const spellBits: [number, Spell][][] = [
  [
    [1, Spell.SummonBoat],
    [2, Spell.ScuttleBoat],
    [4, Spell.Visions],
    [8, Spell.ViewEarth],
    [16, Spell.Disguise],
    [32, Spell.ViewAir],
    [64, Spell.Fly],
    [128, Spell.WaterWalk],
  ],
  [
    [1, Spell.DimensionDoor],
    [2, Spell.TownPortal],
    [4, Spell.QuickSand],
    [8, Spell.LandMine],
    [16, Spell.ForceField],
    [32, Spell.FireWall],
    [64, Spell.Earthquake],
    [128, Spell.MagicArrow],
  ],
  [
    [1, Spell.IceBolt],
    [2, Spell.LightningBolt],
    [4, Spell.Implosion],
    [8, Spell.ChainLightning],
    [16, Spell.FrostRing],
    [32, Spell.Fireball],
    [64, Spell.Inferno],
    [128, Spell.MeteorShower],
  ],
  [
    [1, Spell.DeathRipple],
    [2, Spell.DestroyUndead],
    [4, Spell.Armageddon],
    [8, Spell.Shield],
    [16, Spell.AirShield],
    [32, Spell.FireShield],
    [64, Spell.ProtectionFromAir],
    [128, Spell.ProtectionFromFire],
  ],
  [
    [1, Spell.ProtectionFromWater],
    [2, Spell.ProtectionFromEarth],
    [4, Spell.AntiMagic],
    [8, Spell.Dispel],
    [16, Spell.MagicMirror],
    [32, Spell.Cure],
    [64, Spell.Resurrection],
    [128, Spell.AnimateDead],
  ],
  [
    [1, Spell.Sacrifice],
    [2, Spell.Bless],
    [4, Spell.Curse],
    [8, Spell.Bloodlust],
    [16, Spell.Precision],
    [32, Spell.Weakness],
    [64, Spell.StoneSkin],
    [128, Spell.DisruptingRay],
  ],
  [
    [1, Spell.Prayer],
    [2, Spell.Mirth],
    [4, Spell.Sorrow],
    [8, Spell.Fortune],
    [16, Spell.Misfortune],
    [32, Spell.Haste],
    [64, Spell.Slow],
    [128, Spell.Slayer],
  ],
  [
    [1, Spell.Frenzy],
    [2, Spell.TitansLightningBolt],
    [4, Spell.Counterstrike],
    [8, Spell.Berserk],
    [16, Spell.Hypnotize],
    [32, Spell.Forgetfulness],
    [64, Spell.Blind],
    [128, Spell.Teleport],
  ],
  [
    [1, Spell.RemoveObstacle],
    [2, Spell.Clone],
    [4, Spell.FireElemental],
    [8, Spell.EarthElemental],
    [16, Spell.WaterElemental],
    [32, Spell.AirElemental],
  ],
]

export const spellsMask = bitMasksArray(bytes(9), spellBits)
