export enum HeroClass {
  Knight = 'Knight',
  Cleric = 'Cleric',
  Ranger = 'Ranger',
  Druid = 'Druid',
  Alchemist = 'Alchemist',
  Wizard = 'Wizard',
  Demoniac = 'Demoniac',
  Heretic = 'Heretic',
  DeathKnignt = 'DeathKnignt',
  Necromancer = 'Necromancer',
  Overlord = 'Overlord',
  Warlock = 'Warlock',
  Barbarian = 'Barbarian',
  BattleMage = 'BattleMage',
  Beastmaster = 'Beastmaster',
  Witch = 'Witch',
  Planeswalker = 'Planeswalker',
  Elementalist = 'Elementalist',
}
